name: Build DEV Jars

on: [push, pull_request]

jobs:
  build_dev_jars:
    name: Build DEV jars
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Build with Maven
        run: |
          mvn package
          git_hash=$(git rev-parse --short "$GITHUB_SHA")
          echo "git_hash=$git_hash" >> $GITHUB_ENV
          echo "artifactPath=$(pwd)/target" >> $GITHUB_ENV
      - name: Extract Maven project version
        run: echo ::set-output name=version::$(mvn -q -Dexec.executable=echo -Dexec.args='${project.version}' --non-recursive exec:exec)
        id: project

      - name: Upload Plugin jar
        uses: actions/upload-artifact@v3
        with:
          name: Playtime-${{ env.snapshotVersion }}-${{ env.git_hash }}.jar
          path: ${{ env.artifactPath }}/specialarrows-${{ steps.project.outputs.version }}.jar

      - name: send message
        uses: appleboy/discord-action@master
        with:
          webhook_id: ${{ secrets.WEBHOOK_ID }}
          webhook_token: ${{ secrets.WEBHOOK_TOKEN }}
          file: ${{ env.artifactPath }}/specialarrows-${{ steps.project.outputs.version }}.jar
          message: "New SpecialArrows build: ${{ steps.project.outputs.version }} - ${{ env.git_hash }}"
          color: "#48f442"
          username: "SpecialArrows Builds"
